-- KEYWORDS: ADJECTIVES
INSERT INTO keywords (keyword, type) VALUES 
  ('blur', 'adjective'),
  ('shiok', 'adjective'),
  ('kiasu', 'adjective'),
  ('siao', 'adjective'),
  ('sian', 'adjective'),
  ('paiseh', 'adjective'),
  ('atas', 'adjective'),
  ('shag', 'adjective'),
  ('kaypoh', 'adjective'),
  ('cheem', 'adjective'),
  ('kancheong', 'adjective'),
  ('adorable', 'adjective'),
  ('adventurous', 'adjective'),
  ('aggressive', 'adjective'),
  ('bloody', 'adjective'),
  ('beautiful', 'adjective'),
  ('bewildered', 'adjective'),
  ('cautious', 'adjective'),
  ('charming', 'adjective'),
  ('cheerful', 'adjective'),
  ('defeated', 'adjective'),
  ('depressed', 'adjective'),
  ('doubtful', 'adjective'),
  ('eager', 'adjective'),
  ('embarrassed', 'adjective'),
  ('enthusiastic', 'adjective'),
  ('fierce', 'adjective'),
  ('frantic', 'adjective'),
  ('frightened', 'adjective'),
  ('glamorous', 'adjective'),
  ('grumpy', 'adjective'),
  ('glorious', 'adjective'),
  ('healthy', 'adjective'),
  ('helpless', 'adjective'),
  ('horrible', 'adjective'),
  ('ill', 'adjective'),
  ('important', 'adjective'),
  ('impossible', 'adjective'),
  ('jolly', 'adjective'),
  ('jealous', 'adjective'),
  ('jittery', 'adjective'),
  ('lazy', 'adjective'),
  ('lonely', 'adjective'),
  ('lively', 'adjective'),
  ('magnificent', 'adjective'),
  ('motionless', 'adjective'),
  ('muddy', 'adjective'),
  ('naughty', 'adjective'),
  ('nervous', 'adjective'),
  ('nice', 'adjective'),
  ('obedient', 'adjective'),
  ('obnoxious', 'adjective'),
  ('old-fashioned', 'adjective'),
  ('panicky', 'adjective'),
  ('poor', 'adjective'),
  ('proud', 'adjective'),
  ('quaint', 'adjective'),
  ('relieved', 'adjective'),
  ('repulsive', 'adjective'),
  ('rich', 'adjective'),
  ('selfish', 'adjective'),
  ('shiny', 'adjective'),
  ('sleepy', 'adjective'),
  ('talented', 'adjective'),
  ('tasty', 'adjective'),
  ('tense', 'adjective'),
  ('ugly', 'adjective'),
  ('unusual', 'adjective'),
  ('uptight', 'adjective'),
  ('vast', 'adjective'),
  ('victorious', 'adjective'),
  ('vivacious', 'adjective'),
  ('weary', 'adjective'),
  ('wicked', 'adjective'),
  ('witty', 'adjective'),
  ('zany', 'adjective'),
  ('zealous', 'adjective');

-- KEYWORDS: VERBS
INSERT INTO keywords (keyword, type) VALUES 
  ('sabo', 'verb'),
  ('lepak', 'verb'),
  ('chope', 'verb'),
  ('makan', 'verb'),
  ('jio', 'verb'),
  ('dabao', 'verb'),
  ('tahan', 'verb'),
  ('kena', 'verb'),
  ('paktor', 'verb'),
  ('chiong', 'verb'),
  ('abandon', 'verb'),
  ('admire', 'verb'),
  ('annoy', 'verb'),
  ('behave', 'verb'),
  ('blame', 'verb'),
  ('boast', 'verb'),
  ('complain', 'verb'),
  ('compete', 'verb'),
  ('clap', 'verb'),
  ('describe', 'verb'),
  ('drag', 'verb'),
  ('dance', 'verb'),
  ('educate', 'verb'),
  ('embrace', 'verb'),
  ('endure', 'verb'),
  ('faint', 'verb'),
  ('fidget', 'verb'),
  ('focus', 'verb'),
  ('giggle', 'verb'),
  ('greet', 'verb'),
  ('guess', 'verb'),
  ('hallucinate', 'verb'),
  ('hesitate', 'verb'),
  ('howl', 'verb'),
  ('imitate', 'verb'),
  ('impede', 'verb'),
  ('interrupt', 'verb'),
  ('jeer', 'verb'),
  ('judge', 'verb'),
  ('jaywalk', 'verb'),
  ('kill', 'verb'),
  ('kiss', 'verb'),
  ('knock', 'verb'),
  ('laugh', 'verb'),
  ('lick', 'verb'),
  ('listen', 'verb'),
  ('match', 'verb'),
  ('mingle', 'verb'),
  ('mourn', 'verb'),
  ('need', 'verb'),
  ('nurture', 'verb'),
  ('navigate', 'verb'),
  ('opine', 'verb'),
  ('ooze', 'verb'),
  ('outsmart', 'verb'),
  ('pick', 'verb'),
  ('prohibit', 'verb'),
  ('possess', 'verb'),
  ('queue', 'verb'),
  ('quiz', 'verb'),
  ('quarantine', 'verb'),
  ('read', 'verb'),
  ('resent', 'verb'),
  ('rasp', 'verb'),
  ('saunter', 'verb'),
  ('shout', 'verb'),
  ('skate', 'verb'),
  ('turn', 'verb'),
  ('tackle', 'verb'),
  ('tolerate', 'verb'),
  ('update', 'verb'),
  ('usher', 'verb'),
  ('underestimate', 'verb'),
  ('vaccinate', 'verb'),
  ('view', 'verb'),
  ('vomit', 'verb'),
  ('wonder', 'verb'),
  ('whisper', 'verb'),
  ('wrestle', 'verb'),
  ('yawn', 'verb'),
  ('yell', 'verb'),
  ('yammer', 'verb'),
  ('yank', 'verb'),
  ('zap', 'verb'),
  ('zoom', 'verb'),
  ('zone', 'verb');

-- KEYWORDS: ADVERBS
INSERT INTO keywords (keyword, type) VALUES 
  ('achingly', 'adverb'),
  ('angrily', 'adverb'),
  ('annoyingly', 'adverb'),
  ('anxiously', 'adverb'),
  ('badly', 'adverb'),
  ('boastfully', 'adverb'),
  ('dejectedly', 'adverb'),
  ('enviously', 'adverb'),
  ('foolishly', 'adverb'),
  ('hopelessly', 'adverb'),
  ('irritably', 'adverb'),
  ('jealously', 'adverb'),
  ('joylessly', 'adverb'),
  ('lazily', 'adverb'),
  ('miserably', 'adverb'),
  ('morosely', 'adverb'),
  ('obnoxiously', 'adverb'),
  ('painfully', 'adverb'),
  ('poorly', 'adverb'),
  ('rudely', 'adverb'),
  ('sadly', 'adverb'),
  ('selfishly', 'adverb'),
  ('terribly', 'adverb'),
  ('unhappily', 'adverb'),
  ('wearily', 'adverb'),
  ('boldly', 'adverb'),
  ('bravely', 'adverb'),
  ('brightly', 'adverb'),
  ('cheerfully', 'adverb'),
  ('deftly', 'adverb'),
  ('devotedly', 'adverb'),
  ('eagerly', 'adverb'),
  ('elegantly', 'adverb'),
  ('faithfully', 'adverb'),
  ('fortunately', 'adverb'),
  ('gleefully', 'adverb'),
  ('gracefully', 'adverb'),
  ('happily', 'adverb'),
  ('honestly', 'adverb'),
  ('innocently', 'adverb'),
  ('kindly', 'adverb'),
  ('merrily', 'adverb'),
  ('obediently', 'adverb'),
  ('perfectly', 'adverb'),
  ('politely', 'adverb'),
  ('powerfully', 'adverb'),
  ('safely', 'adverb'),
  ('victoriously', 'adverb'),
  ('warmly', 'adverb'),
  ('vivaciously', 'adverb');

-- KEYWORDS: NOUNS
INSERT INTO keywords (keyword, type) VALUES 
  ('anger', 'noun'),
  ('athlete', 'noun'),
  ('avalanche', 'noun'),
  ('baby', 'noun'),
  ('body', 'noun'),
  ('brain', 'noun'),
  ('cancer', 'noun'),
  ('church', 'noun'),
  ('colour', 'noun'),
  ('dictator', 'noun'),
  ('dozen', 'noun'),
  ('dwarf', 'noun'),
  ('eagle', 'noun'),
  ('epic', 'noun'),
  ('explosion', 'noun'),
  ('failure', 'noun'),
  ('family', 'noun'),
  ('field', 'noun'),
  ('genius', 'noun'),
  ('gossip', 'noun'),
  ('guitar', 'noun'),
  ('hawker centre', 'noun'),
  ('hdb', 'noun'),
  ('heaven', 'noun'),
  ('hobby', 'noun'),
  ('hospital', 'noun'),
  ('idea', 'noun'),
  ('igloo', 'noun'),
  ('impact', 'noun'),
  ('jackpot', 'noun'),
  ('jewel', 'noun'),
  ('joker', 'noun'),
  ('journal', 'noun'),
  ('kampong', 'noun'),
  ('ketchup', 'noun'),
  ('killer litter', 'noun'),
  ('kilogram', 'noun'),
  ('koala', 'noun'),
  ('kopi', 'noun'),
  ('laser', 'noun'),
  ('lifestyle', 'noun'),
  ('limpeh', 'noun'),
  ('lobang', 'noun'),
  ('luck', 'noun'),
  ('milo', 'noun'),
  ('mission', 'noun'),
  ('moment', 'noun'),
  ('muscle', 'noun'),
  ('nature', 'noun'),
  ('neighbourhood', 'noun'),
  ('nursery', 'noun'),
  ('ogre', 'noun'),
  ('option', 'noun'),
  ('orange', 'noun'),
  ('party', 'noun'),
  ('plan', 'noun'),
  ('police', 'noun'),
  ('quality', 'noun'),
  ('queen', 'noun'),
  ('quicksand', 'noun'),
  ('reason', 'noun'),
  ('recipe', 'noun'),
  ('risk', 'noun'),
  ('roti prata', 'noun'),
  ('secret', 'noun'),
  ('shadow', 'noun'),
  ('sotong', 'noun'),
  ('soulmate', 'noun'),
  ('thing', 'noun'),
  ('ticket', 'noun'),
  ('truth', 'noun'),
  ('ulcer', 'noun'),
  ('underdog', 'noun'),
  ('upside', 'noun'),
  ('vegan', 'noun'),
  ('victim', 'noun'),
  ('vision', 'noun'),
  ('waste', 'noun'),
  ('weekend', 'noun'),
  ('wet market', 'noun'),
  ('window', 'noun'),
  ('x-factor', 'noun'),
  ('x-ray', 'noun'),
  ('xenophobia', 'noun'),
  ('yam', 'noun'),
  ('year', 'noun'),
  ('yoga', 'noun'),
  ('zebra', 'noun'),
  ('zillion', 'noun'),
  ('zip', 'noun');

-- PARAGRAPHS: STARTING
INSERT INTO starting_paragraphs (paragraph) VALUES
  ('Mr. and Mrs. {{name}}, of 415 Hougang Avenue 10, were proud to say that they were perfectly normal, thank you very much. They were the last people you’d expect to be involved in anything strange or mysterious, because they just didn’t hold with such nonsense.'),
  ('{{name}}, of Jalan Ubin Farm, had locked the hen-houses for the night, but was too drunk to remember to shut the pop-holes. With the ring of light from their lantern dancing from side to side, they lurched across the yard, kicked off their boots at the back door, drew themselves a last can of Tiger from their mini-fridge, and made their way up to bed, where their spouse was already snoring.'),
  ('A merry little surge of electricity piped by automatic alarm from the mood organ beside their bed awakened {{name}}. Surprised - it always surprised them to find themselves awake without prior notice - they rose from the bed, stood up in their Marks & Spencer pyjamas, and stretched. Now, in their bed, {{name}}''s spouse opened their grey, unmerry eyes, blinked, then groaned and shut their eyes again.'),
  ('{{name}} was very rich and very peculiar, and had been the wonder of Namly Avenue for thirty years, ever since their remarkable disappearance and unexpected return. The riches {{name}} had brought back from their travels had now become a Bukit Timah legend, and it was properly believed, whatever the old folk might say, that their bungalow was full of tunnels filled with treasure. And if that was not enough for fame, there was also their prolonged vigour to marvel at. Time wore on, but it seemed to have little effect on {{name}}. At ninety they were much the same as at fifty. At ninety-nine they began to call {{name}} well-preserved; but unchanged would have been nearer the mark.'),
  ('{{name}} was an elderly who fished alone in a sampan in Jelutong River and they had gone eighty-four days now without taking a fish. In the first forty days a boy had been with {{name}}. But after forty days without a fish the boy’s parents had told him that {{name}} was now definitely sibei suay, which is the worst form of unlucky, and the boy had gone at their orders in another boat which caught three good fish the first week. It made the boy sad to see the elderly come in each day with their sampan empty and he always went down to help them carry either the coiled lines or the gaff and harpoon and the sail that was furled around the mast. The sail was patched with flour sacks and, furled, it looked like the flag of permanent defeat.'),
  ('{{name}} lowered themselves down the last few feet of rock and began to pick their way toward the jungle. Though {{name}} had taken off their school prefect tie and trailed it now from one hand, their grey shirt stuck to them and their hair was plastered to their forehead. All round them the long scar smashed into the jungle was a bath of heat. {{name}} was clambering heavily among the creepers and broken trunks when a bird, a vision of red and yellow, flashed upwards with a witchlike cry; and this cry was echoed by another.'),
  ('All this happened, more or less. The war parts, anyway, are pretty much true. One guy I knew really was stabbed in Lucky Plaza for asking the wrong girl for her number. Another guy I knew really did threaten to have his personal enemies killed by local gangsters. And so on.'),
  ('{{name}} slept in what had once been a badminton court. The floor was of varnished wood, with stripes painted on it, for the games that were formerly played there; the poles were still in place, though the nets were gone. A balcony ran around the hall, for the spectators, and {{name}} thought they could smell, faintly like an afterimage, the pungent scent of sweat, shot through with the sweet taint of mints and perfume from the watching girls, felt-skirted as they knew from pictures, later in miniskirts, then pants, then in one earring, spiky green-streaked hair. Dances would have been held there; the music lingered, a palimpsest of unheard sound, style upon style, an undercurrent of drums, a forlorn wail, garlands made of tissue-paper flowers, cardboard devils, a revolving ball of mirrors, powdering the dancers with a snow of light.'),
  ('“Where’s Papa going with that cleaver?" said {{name}} to their mother as they were setting the table for breakfast. "Out to the coop," replied the mother. "Some chicks were born last night." "I don''t see why he needs an cleaver," continued {{name}}, who was only eight.'),
  ('Boys were playing basketball around a lamp post with a backboard recklessly hooked to it. Legs, shouts. The scrape and snap of Converses on loose asphalt seemed to catapult their voices high into the moist March air blue above the HDB flats. {{name}}, known infamously as Rabbit, came up the alley in a business suit, stopped and watched, though they were twenty-six and above 180cm tall. So tall, {{name}} seemed an unlikely rabbit, but the breadth of pale face, the pallor of their grey irises, and a nervous flutter under their brief nose as they stabbed a cigarette into their mouth partially explained the nickname, which was given to {{name}} when they too were a child. {{name}} stood there thinking, the kids keep coming, they keep crowding you up.'),
  ('‘This must be a simply enormous cupboard!’ {{name}} thought, going still further in and pushing the soft folds of the coats aside to make room for them. Then {{name}} noticed that there was something crunching under their feet. ‘I wonder is that more moth balls?’ {{name}} thought, stooping down to feel it with their hands. But instead of feeling the hard, smooth wood of the floor of the cupboard, {{name}} felt something soft and powdery and extremely cold. ‘This is very weird,’ {{name}} said, and went on a step or two further.'),
  ('After hearing the disgusting noises from downstairs last night, {{name}} had vowed never to drink alcohol. Their father got the dog drunk on Heineken at the party last night. If the SPCA hear about it he could get done. Eight days have gone by since Christmas Day but {{name}}''s mother still hadn’t worn the green apron they bought her for Christmas!'),
  ('The residents of Seletar Hills Estate still called it "the {{name}} House," even though it had been many years since the {{name}} family had lived there. It stood on a tiny slope overlooking the estate, some of its windows boarded, tiles missing from its roof, and ivy spreading unchecked over its face. Once a fine-looking semi-detached, and easily the largest and grandest building in the neighbourhood around, the {{name}} House was now damp, derelict, and unoccupied.'),
  ('The two men appeared out of nowhere, a few yards apart along the barely lit Jalan Mempurong Gateway. For a second they stood quite still, wands directed at each other’s chests; then, recognizing each other, they stowed their wands beneath their cloaks and started walking briskly in the same direction. “News?” asked the taller of two. “The best,” replied {{name}}.'),
  ('{{name}} sped on up the hill. Every now and again {{name}} bent to the ground. The rats go light, and their footprints are not easy even for an exterminator to read, but not far from the top a drain crossed the path, and in the concrete they saw what they were seeking.');

-- PARAGRAPHS: ENDING
INSERT INTO ending_paragraphs (paragraph) VALUES
  ('“Oh, I will,” said {{name}}, and they were surprised at the grin that was spreading over {{name}}''s face. “They don’t know we’re not allowed to use magic at home. I’m going to have a lot of fun with them this summer…”'),
  ('Twelve voices were shouting in anger, and they were all alike. No question, now, what had happened to the faces of the boars. The creatures outside looked from boar to man, and from man to boar, and from boar to man again; but already it was impossible to say which was which.'),
  ('The clerk said, "For the aquarium luohan I''d suggest also a perpetually renewing puddle, unless it''s a Zhenzhu, in which case there''s a kit containing sand, multicolored pebbles, and bits of organic debris. And if you''re going to be putting it through its feed cycle regularly I suggest you let our service department make a periodic jaw adjustment. In a luohan that''s vital." "Fine," {{name}} said. "I want it to work perfectly. My partner is devoted to it." {{name}} gave their address and hung up. And, feeling better, fixed themselves at last a cup of hot Ovaltine.'),
  ('Then shouldering their burdens, {{name}} set off, seeking a path that would bring them over the vast fields of the Green Corridor, and down into the now-defunct Tanjong Pagar Railway Station.'),
  ('Up the road, in his kampong, {{name}} was sleeping again. They were still sleeping on their face and the boy was sitting by them watching them. {{name}} was dreaming about the otters.'),
  ('The officer, surrounded by these noises, was moved and a little embarrassed. He turned away to give {{name}} time to pull themselves together; and waited, allowing his eyes to rest on the Fast Response Car in the distance. '),
  ('{{name}} wandered out onto the shady street. The trees were leafing out. There was nothing going on out there, no traffic of any kind. There was only one vehicle, an abandoned Nissan NV200. After everything, the van almost looked like a hearse. Birds were talking. One bird said to {{name}}, “Can or not?”'),
  ('The van waited in the driveway, its double doors stood open. The two of them, one on either side now, took {{name}} by the elbows to help them in. Whether this is {{name}}''s end or a new beginning {{name}} had no way of knowing: {{name}} had given themselves over into the hands of strangers, because it couldn''t be helped. And so {{name}} stepped up, into the darkness within; or else the light.'),
  ('Rango never forgot {{name}}. Although he loved his children and grandchildren dearly, none of the new house lizards ever quite took her place in his heart. {{name}} was in a class by themselves. It is not often that someone comes along who is a true friend and a good writer. {{name}} was both.'),
  ('{{name}} came to the curb but instead of going to their right and around the block they stepped down, with as big a feeling as if this little alley was a wide river, and crossed. {{name}} wanted to travel to the next sidewalk. Although this block of brick was just like the one they left, something in it made them happy; the steps and windowsills seemed to twitch and shift in the corner of their eye, alive. This illusion tripped {{name}}. Their hands lifted of their own and they felt the wind on their ears even before, their heels hitting heavily on the pavement at first but with an effortless gathering out of a kind of sweet panic growing lighter and quicker and quieter, {{name}} ran, and ran, and ran.'),
  ('"Indeed, don’t try to get there at all. It’ll happen when you’re not looking for it. And don’t talk too much about it even among yourselves. And don’t mention it to anyone else unless you find that they’ve had adventures of the same sort themselves. What’s that? How will you know? Oh, you’ll know all right. Odd things they say — even their looks — will let the secret out. Keep your eyes open. Bless me, what do they teach them at these schools?" {{name}} mused.'),
  ('{{name}} had just had the most humiliating experience of their life. It started when they began to assemble my model aeroplane. {{name}} had nearly finished it when they thought they would try an experimental sniff of glue. {{name}} put their nose to the undercarriage and sniffed for five seconds, nothing spiritual happened but their nose stuck to the plane! {{name}}''s father took them to A&E to have it removed, how they endured the laughing and sniggering {{name}} didn’t know. The doctor wrote ‘Glue Sniffer’ on {{name}}''s outpatient’s card.'),
  ('The rest of the journey passed pleasantly enough; {{name}} wished it could have gone on all night, in fact, and that they would never arrive at Changi Airport… but as {{name}} had learned the hard way that year, time will not slow down when something unpleasant lies ahead, and all too soon, the MRT was pulling in at the station. The usual noise filled the station as the passengers began to disembark, carrying their luggage. {{name}}, however, stayed put.'),
  ('As {{name}} looked at her, they lowered their hand absentmindedly and touched the lightning scar on their forehead. The scar had not pained {{name}} for years. All was well.'),
  ('The great doors slammed to. Boom. The bars of iron fell into place inside. Clang. The gate was shut. {{name}} hurled themselves against the bolted brazen plates and fell senseless to the ground. {{name}} was out in the darkness. Their partner was alive but taken by the enemy.');